services:
  postgres:
    image: postgres:18
    container_name: postgres18
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: AdStar2310
      POSTGRES_DB: postgres_ecom
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
